name: Update Docker Hub Description

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  dockerhub-desc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: imansur/pjsua2-call-agent
          readme-filepath: ./README.md
